---
title: "project euler problem 36: double-base palindromes"
author: "chad allison | 23 july 2023"
output: github_document
knit: (function(input, ...) { rmarkdown::render(input, output_file = "README.md", envir = globalenv()) })
---

___

### setup

```{r message = F, warning = F}
library(tidyverse)
options(digits = 22, scipen = 999)
```

### solution

```{r}
# function to check if a number is palindromic
is_palindrome = function(number) {
  num_str = as.character(number)
  rev_num_str = rev(strsplit(num_str, '')[[1]])
  return(num_str == paste(rev_num_str, collapse = ''))
}

# function to find palindromic numbers and their binary counterparts
find_palindromic_numbers = function(limit) {
  palindromic_numbers = c()
  for (num in 0:(limit - 1)) {
    if (is_palindrome(num)) {
      binary_num = as.character(as.binary(num))
      if (is_palindrome(binary_num)) {
        palindromic_numbers = c(palindromic_numbers, num)
      }
    }
  }
  return(palindromic_numbers)
}

# function to convert base 10 to base 2
as.binary = function(x) {
  res = ""
  while (x > 0) {
    res = paste(x %% 2, res, sep = "")
    x = floor(x / 2)
  }
  return(res)
}

# setting limit, getting all palindromic numbers up to limit and summing
limit = 1000000
palindromic_numbers = find_palindromic_numbers(limit)
sum(palindromic_numbers)
```















