<<<<<<< HEAD
---
title: "project euler problem 28: number spiral diagonals"
author: "chad allison | 05 january 2023"
output: github_document
---

___

### setup

```{r message = F, warning = F}
library(tidyverse)
options(digits = 22, scipen = 999)
```

### creating function to solve

```{r}
diag_sum = function(size) {
  ans = 1
  for (i in 3:size) {
    if (i %% 2 == 1) ans = ans + sum(4 * i ^ 2 - 6 * (i - 1))
  }
  return(as.character(ans))
}

diag_sum(5)
```

### solution

```{r}
diag_sum(1001)
```

















=======
---
title: "project euler problem 28: number spiral diagonals"
author: "chad allison | 05 january 2023"
output: github_document
---

___

### setup

```{r message = F, warning = F}
library(tidyverse)
options(digits = 22, scipen = 999)
```

### creating function to solve

```{r}
diag_sum = function(size) {
  ans = 1
  for (i in 3:size) {
    if (i %% 2 == 1) ans = ans + sum(4 * i ^ 2 - 6 * (i - 1))
  }
  return(as.character(ans))
}

diag_sum(5)
```

### solution

```{r}
diag_sum(1001)
```

















>>>>>>> f1222a78a7a34ae61e1902ab8e4bede3dfa4665f
