---
title: "project euler problem 17: number letter counts"
author: "chad allison | 29 december 2022"
output: github_document
---

___

### setup

```{r message = F, warning = F}
library(tidyverse)
library(english)
options(digits = 22, scipen = 999)
```

### reproducing example

```{r}
data.frame(num = 1:5) |>
  mutate(written = as.character(english(num)),
         chars = nchar(written))

data.frame(num = 1:5) |>
  mutate(written = as.character(english(num)),
         chars = nchar(written)) |>
  summarise(letters = sum(chars)) |>
  pull(letters)
```

### solution

```{r}
data.frame(num = 1:1000) |>
  mutate(written = str_remove_all(as.character(english(num)), "[ -]"),
         written = ifelse(str_detect(written, "hundred") &
                          substr(written, nchar(written) - 6, nchar(written)) != "hundred",
                          str_replace_all(written, "hundred", "hundredand"), written),
         chars = nchar(written)) |>
  sample_n(10) |>
  arrange(num)

data.frame(num = 1:1000) |>
  mutate(written = str_remove_all(as.character(english(num)), "[ -]"),
         written = ifelse(str_detect(written, "hundred") &
                          substr(written, nchar(written) - 6, nchar(written)) != "hundred",
                          str_replace_all(written, "hundred", "hundredand"), written),
         chars = nchar(written)) |>
  summarise(n = sum(chars)) |>
  pull(n)
```



























