---
title: "project euler problem 39: integer right triangles"
author: "chad allison | 25 july 2023"
output: github_document
knit: (function(input, ...) { rmarkdown::render(input, output_file = "README.md", envir = globalenv()) })
---

___

### setup

```{r message = F, warning = F}
library(tidyverse)
options(digits = 22, scipen = 999)
```

### solution

```{r}
# setting upper limit
limit = 1000

# function to count number of solutions for a given p
count_solutions = function(p) {
  count = 0
  for (a in 1:(p %/% 3)) { # a must be less than p / 3
    for (b in a:((p - a) %/% 2 + 1)) { # b must be less than (p - a) / 2
      c = p - a - b
      if (a ^ 2 + b ^ 2 == c ^ 2) count = count + 1
    }
  }
  return(count)
}

# creating variables for optimal p and number of solutions for that p
max_p = 0
max_solutions = 0

# looping through every p up to the limit
for (i in 1:limit) {
  num_solutions = count_solutions(i)
  if (num_solutions > max_solutions) {
    max_solutions = num_solutions
    max_p = i
  }
}

# solution
paste0("optimal p = ", max_p, " with ", max_solutions, " solutions")
```

























